sudo: required
services:
  - docker

language: generic

env:
  matrix:
    - ARCH_SUFFIX= CC=gcc ARCH_NATIVE=1 MINIMAL=
    - ARCH_SUFFIX=amd64 CC=gcc ARCH_NATIVE=1 MINIMAL=
    - ARCH_SUFFIX=amd64 CC=gcc ARCH_NATIVE=1 MINIMAL=1
    - ARCH_SUFFIX=arm64 CC=aarch64-linux-gnu-gcc ARCH_NATIVE= MINIMAL=
    - ARCH_SUFFIX=armel CC=arm-linux-gnueabi-gcc ARCH_NATIVE= MINIMAL=
    - ARCH_SUFFIX=armhf CC=arm-linux-gnueabihf-gcc ARCH_NATIVE= MINIMAL=
    - ARCH_SUFFIX=i386 CFLAGS="-m32" ARCH_NATIVE= MINIMAL=
    - ARCH_SUFFIX=muslc-amd64 CC=musl-gcc ARCH_NATIVE=1 MINIMAL=
    - ARCH_SUFFIX=ppc64el CC=powerpc64le-linux-gnu-gcc ARCH_NATIVE= MINIMAL=
    - ARCH_SUFFIX=s390x CC=s390x-linux-gnu-gcc ARCH_NATIVE= MINIMAL=
  global:
    - secure: "RKF9Z9gLxp6k/xITqn7ma1E9HfpYcDXuJFf4862WeH9EMnK9lDq+TWnGsQfkIlqh8h9goe7U+BvRiTibj9MiD5u7eluLo3dlwsLxPpYtyswYeLeC1wKKdT5LPGAXbRKomvBalRYMI+dDnGIM4w96mHgGGvx2zZXGkiAQhm6fJ3k="
    - DIST_DIR="${PWD}/dist"

before_install:
  - openssl aes-256-cbc -K $encrypted_2893fd5649e7_key -iv $encrypted_2893fd5649e7_iv -in sign.key.enc -out sign.key -d || echo "Encrypted signing key unavailable"

script:
  - ./ddist.sh "$ARCH_SUFFIX"
  - ls -lah "$DIST_DIR"
  - git diff --exit-code

deploy:
  provider: releases
  api_key:
    secure: "emR9hLjjmNqWcCWYGaRCXTTCXsbSvaIOIfuN4cFwQmlhgNz00obCI9IhN5n77k9RGtKs5j8QL7tzcRiK4XhScCywUIs4OtSV6gL7hmQLkFvcMit/NMsmmI7UbevsQyGFh3McDEcTV9OI3HeXfUMgD4+K2DcpJ+Bb4QjHcSuGnqYRC1ClfeNTkwLfnZmaxGWy9F5LYoV3SBrE8Rxleao8hX3Spch3XN/z+B+CG7oSXFNucLW8urDIR1dLlXsA2N7CRSI/O46HE6WBnBAqpIhGqC6kzygXGSRP7KnllZmeJNgzSMFsR1l1FGzZVdylKtCop+m0RQKqUqLFdVM8wDlvXMRyJvks6RDZVMTQDHGujJORE4qSSsy6zJ05nb8s0qft6JGp3ADRJZhJ7u7Yz5yWYT/iUOMnVMXmXaNG+QyapkiwWeyPnU9n0FVkLUjSKyAagUrmfaP8baBFzjON4Lbm03JlZOukCPJIkT2UYMRBZSCkvD6GhcAwhm8EW0Tqp0lr4xVUn+l6MgH9WSSSpYnORkYVNJvXmk6HadyePbLUTOrfzjNmMCkSdVPoc6afBbIPRJDvXcw0Oh5pe7/GppazLZ19cfkma8FHvnCtj+eGIgzAWX0uR7SbuO11zhXW9zH3pFQ8hcm0gJ0Z3L0IZuh+2jiusQQOE22oVIFCu1PMn/Q="
  file: "${DIST_DIR}/*"
  file_glob: true
  skip_cleanup: true
  on:
    repo: zambon/tini
    tags: true
    condition: '-z "$MINIMAL"'
